apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: critical-path-uploads
  namespace: critical-path
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi
