apiVersion: v1
kind: ServiceAccount
metadata:
  name: critical-path-api
  namespace: critical-path
  annotations:
    iam.gke.io/gcp-service-account: critical-path-api@realm-construction.iam.gserviceaccount.com
