/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppUser {
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  password_hash: string;
}

export interface BoardColumn {
  created_at: Generated<Timestamp>;
  id: string;
  is_done: Generated<boolean>;
  name: string;
  position: number;
  project_id: string;
}

export interface Label {
  color: string;
  id: string;
  name: string;
  project_id: string;
}

export interface Project {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: string;
  is_template: Generated<boolean>;
  name: string;
}

export interface Session {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  token_hash: string;
  user_id: string;
}

export interface Task {
  column_id: string;
  created_at: Generated<Timestamp>;
  description: Json | null;
  id: string;
  position: number;
  project_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface TaskAssignee {
  task_id: string;
  user_id: string;
}

export interface TaskDependency {
  blocked_task_id: string;
  blocker_task_id: string;
  created_at: Generated<Timestamp>;
}

export interface TaskImage {
  content_type: string;
  created_at: Generated<Timestamp>;
  filename: string;
  id: string;
  size_bytes: number;
  storage_key: string;
  task_id: string;
}

export interface TaskLabel {
  label_id: string;
  task_id: string;
}

export interface DB {
  app_user: AppUser;
  board_column: BoardColumn;
  label: Label;
  project: Project;
  session: Session;
  task: Task;
  task_assignee: TaskAssignee;
  task_dependency: TaskDependency;
  task_image: TaskImage;
  task_label: TaskLabel;
}
